sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-extra
    - latex-beamer
    - pgf
    - python-pygments
    - ghostscript
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: change
    on_failure: always
